version: '3'
services:
    apache:
        build: .docker/apache
        container_name: ${APP_NAME}_apache
        ports:
          - 8000:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./app/:/home/www
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: ${APP_NAME}_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${APP_NAME}
            MYSQL_USER: root
            MYSQL_PASSWORD: root

    php:
        build: .docker/php
        container_name: ${APP_NAME}_php
        volumes:
          - ./app/:/home/www
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql